defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV['TWITTER_ACCESS_BOT'] %>
    consumer_secret: <%= ENV['TWITTER_SECRET_BOT'] %>
    callback_url: http://localhost:3000/bots/auth/twitter/callback
    retweet_potential_number: 100
    follow_potential_number: 10

test:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV['TWITTER_ACCESS_BOT'] %>
    consumer_secret: <%= ENV['TWITTER_SECRET_BOT'] %>
    callback_url: http://localhost:3000/bots/auth/twitter/callback
    retweet_potential_number: 100
    follow_potential_number: 10

production:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV['TWITTER_ACCESS_BOT'] %>
    consumer_secret: <%= ENV['TWITTER_SECRET_BOT'] %>
    callback_url: http://www.harmox.link/bots/auth/twitter/callback
    retweet_potential_number: 100
    follow_potential_number: 10
